project:
  type: website

website:
  navbar:
    title: Alisa Krasilnikov's Personal Website
    right:
      - href: index.qmd
        text: Home
      - href: personal-projects.qmd
        text: Personal Projects
      - href: stat-541-posts.qmd 
        text: STAT 541 Portfolio
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

